name: Unlighthouse deploy Site with Assertions

on:
  workflow_dispatch:

jobs:
  test-and-deploy-site:
    uses: majesticostudio/.github/.github/workflows/unlighthouse.yml@main
    with:
      unlighthouse_config_file: "./unlighthouse.config.ts"
    secrets:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
